name: Test

on:
  push:
    branches:
      - main
    paths:
      - "lua/**.lua"
      - "plugin/**.lua"
      - "test/**.lua"
      - "test/**.sh"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y gcc g++ git lua5.4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Test TSInstall
        run: bash test/test_install.sh -t 120s -o yaml

      - name: Test TSUninstall
        run: bash test/test_uninstall.sh -t 120s -o yaml

      - name: Test TSUpdate
        run: bash test/test_update.sh -t 120s -o yaml
